### PR TITLE
first draft of pandas exercise notebook

### PR DESCRIPTION
**Pull request by zonca**
Addresses #30 

First draft of an Exercise Notebook for pandas, let's discuss tomorrow at the meeting.

### CODE REVIEW

**Comment by zonca** [comment]
notes for meeting

* how do we want the students to use `nbgrader`?
* isn't easier with asserts?
* feedback on length and complexity.

**Comment by zonca** [comment]
ok, now I created 6 simple exercises and 5 advanced, please take a look to the notebooks, here is the student version with no solutions:

https://github.com/zonca/edX/blob/5f9a8a98627c93ed4ead1c2455ba18fdd1efabae/Exercise%20Notebooks/test1/release/pandas/ex04_1_pandas.ipynb

**Comment by leporter** [comment]
Andrea, I haven't had a chance to go through the notebook yet, but can you look at the changes we made with Alok's today (the header with instructions + the convention of modify/do not modify)?

**Comment by zonca** [comment]
I looked at the header. can you make it general for all the notebooks? Then
we can instruct nbgrader to automatically prepend it to all notebooks​.
I used your same syntax for do not modify

**Comment by leporter** [comment]
Great point - I updated the language in the numpy notebook to be more generic.  Does it seem like it applies for your notebook as well?

**Comment by zonca** [comment]
Yes, I think it could be standard instructions for all exercise notebooks

**Comment by zonca** [comment]
ok, I'll merge this

**Pull request merged**
