### PR TITLE
Setup anaconda swcarpentry

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
see a preview here:

http://htmlpreview.github.io/?https://github.com/zonca/edX/blob/bbec48bd91cd96c950e951a3c5873443debd13bf/setup_gitbash_anaconda/index.html

@altintas @leporter do students need also an editor? The Software Carpentry instructions use `nano`, but I can remove that section and only leave shell and Python.

**Comment by leporter** [comment]
I think nano is fine - if we expected folks to program in the editor we might want vim/emacs but since they should be working in notebooks, I think we're okay.  @altintas do you agree?

**Comment by zonca** [comment]
Check how to get python terminal on windows

**Comment by zonca** [comment]
removed editor, `nano` is not very user friendly anyway...

**Pull request merged**
